version: '3.8'

services:
  mysql:
    image: mysql:8.0  # 使用MySQL 8.0版本
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: "123456"  # 设置root用户的密码
      MYSQL_DATABASE: "knowledge"    # 创建名为knowledge的数据库
    ports:
      - "3306:3306"  # 将容器的3306端口映射到主机的3306端口
    volumes:
      - mysql_data:/var/lib/mysql  # 持久化MySQL数据
    command: --default-authentication-plugin=mysql_native_password  # 使用mysql_native_password插件

volumes:
  mysql_data:  # 定义数据卷
